### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by malith-gammanpila** [madawa-prasad/business-card#1]
https://github.com/madawa-prasad/business-card/blob/31f9df6f94fcd3dc3f74b6003a8586e668aca663/src/components/profile/Profile.jsx#L1-L4

https://github.com/madawa-prasad/business-card/blob/31f9df6f94fcd3dc3f74b6003a8586e668aca663/src/components/footer/Footer.jsx#L1-L7

Keep a line space between library imports and your own imports
Example: 
```
import React from 'react';

import profile from '../../images/profile.jpg';
import email from '../../images/email.png';
import './profile.css';
```

**Comment by madawa-prasad** [comment]
Corrected
